# Generated by Django 4.0.3 on 2022-04-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periphery',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
