# Generated by Django 4.0.3 on 2022-04-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periphery',
            old_name='status',
            new_name='condition',
        ),
    ]
