# Generated by Django 4.0.3 on 2022-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_last_modified_periphery_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='periphery',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
