# Generated by Django 4.0.3 on 2022-04-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_status_periphery_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_of_release',
        ),
        migrations.RemoveField(
            model_name='periphery',
            name='date_of_release',
        ),
    ]
