# Generated by Django 4.0.3 on 2022-04-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_image_periphery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periphery',
            name='warranty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
