# Generated by Django 4.0.3 on 2022-04-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_periphery_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periphery',
            name='warranty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
